// Availity REST API Transaction Support
// Source: Availity Payer List Export CSV (March 2026)
// Contact Sales = Available per contract
// Format: AV = { "Plan Name": [{p:"PID", n:"name", t:{e270:1/0, pa_in:1/0, ...}}] }

const AV={"Anthem Blue Cross":[{"p":"040","n":"ANTHEM BC CALIFORNIA","s":"","t":{e270:1,pa_in:1,pa_out:1,ref:1,pa_det:0}}],
"Anthem Blue Cross and Blue Shield":[{"p":"303","n":"ANTHEM BC NY","s":"303","t":{e270:1,pa_in:1,pa_out:1,ref:1,pa_det:0}},{"p":"803","n":"ANTHEM BCBS NY","s":"803","t":{e270:1,pa_in:1,pa_out:1,ref:1,pa_det:0}}],
"Anthem Blue Cross and Blue Shield Colorado":[{"p":"050","n":"ANTHEM BCBS COLORADO","s":"","t":{e270:1,pa_in:1,pa_out:1,ref:1,pa_det:0}}],
"Anthem Blue Cross and Blue Shield Connecticut":[{"p":"060","n":"ANTHEM BCBS CONNECTICUT","s":"","t":{e270:1,pa_in:1,pa_out:1,ref:1,pa_det:0}}],
"Anthem Blue Cross and Blue Shield Indiana":[{"p":"130","n":"ANTHEM BCBS INDIANA","s":"ANTHEM_IN","t":{e270:1,pa_in:1,pa_out:1,ref:1,pa_det:0}}],
"Anthem Blue Cross and Blue Shield Kentucky":[{"p":"160","n":"ANTHEM BCBS KENTUCKY","s":"ANTHEM_KY","t":{e270:1,pa_in:1,pa_out:1,ref:1,pa_det:0}}],
"Anthem Blue Cross and Blue Shield Maine":[{"p":"180","n":"ANTHEM BCBS MAINE","s":"","t":{e270:1,pa_in:1,pa_out:1,ref:1,pa_det:0}},{"p":"958","n":"ANTHEM MAINEHEALTH","s":"","t":{e270:1,pa_in:1,pa_out:1,ref:1,pa_det:0}}],
"Anthem Blue Cross and Blue Shield Missouri":[{"p":"241","n":"ANTHEM BCBS MISSOURI","s":"ANTHEM_MO","t":{e270:1,pa_in:1,pa_out:1,ref:1,pa_det:0}}],
"Anthem Blue Cross and Blue Shield Nevada":[{"p":"265","n":"Anthem BCBS Nevada","s":"","t":{e270:1,pa_in:1,pa_out:1,ref:1,pa_det:0}}],
"Anthem Blue Cross and Blue Shield New Hampshire":[{"p":"270","n":"ANTHEM BCBS NEW HAMPSHIRE","s":"","t":{e270:1,pa_in:1,pa_out:1,ref:1,pa_det:0}}],
"Anthem Blue Cross and Blue Shield Ohio":[{"p":"332","n":"ANTHEM BCBS OHIO","s":"ANTHEM_OH","t":{e270:1,pa_in:1,pa_out:1,ref:1,pa_det:0}}],
"Anthem Blue Cross and Blue Shield Virginia":[{"p":"423","n":"ANTHEM BCBS VIRGINIA","s":"ANTHEM_VA","t":{e270:1,pa_in:1,pa_out:1,ref:1,pa_det:0}}],
"Anthem Blue Cross and Blue Shield Wisconsin":[{"p":"450","n":"ANTHEM BCBS WISCONSIN","s":"ANTHEM_WI","t":{e270:1,pa_in:1,pa_out:1,ref:1,pa_det:0}}],
"Arkansas Blue Cross and Blue Shield":[{"p":"00520","n":"ARKANSAS BCBS","s":"","t":{e270:1,pa_det:0}}],
"Blue Cross & Blue Shield of Mississippi":[{"p":"100041","n":"BCBS MISSISSIPPI","s":"","t":{e270:1}},{"p":"BCMS","n":"BCBS MISSISSIPPI","s":"","t":{e270:1}}],
"Blue Cross & Blue Shield of Rhode Island":[{"p":"BCRIC","n":"BCBS RHODE ISLAND","s":"","t":{e270:1}}],
"Blue Cross Blue Shield of Arizona":[{"p":"53589","n":"AZ BLUE (BCBS ARIZONA)","s":"BCBSARIZON","t":{e270:1}},{"p":"77078","n":"BLUE CROSS BLUE SHIELD ARIZONA ADVANTAGE","s":"","t":{e270:1}}],
"Blue Cross Blue Shield of Georgia":[{"p":"101","n":"ANTHEM - GA","s":"","t":{e270:1,pa_in:1,pa_out:1,ref:1,pa_det:0}}],
"Blue Cross Blue Shield of Michigan":[{"p":"00710P","n":"BCBS MICHIGAN PROFESSIONAL","s":"00710P","t":{e270:1}},{"p":"00210I","n":"BCBS MICHIGAN INSTITUTIONAL","s":"00210I","t":{e270:1}},{"p":"00710D","n":"BCBS MICHIGAN DENTAL","s":"00710D","t":{e270:1}},{"p":"00710","n":"BCBSM - FEDERAL EMPLOYEE PROGRAM PLANS","s":"BCBSMI","t":{e270:1}}],
"Blue Cross Blue Shield of Wyoming":[{"p":"53767","n":"BCBS WYOMING","s":"BCBSWY","t":{e270:1,pa_in:0,pa_out:0,pa_det:0}}],
"Blue Cross and Blue Shield of Alabama":[{"p":"00510BC","n":"BCBS ALABAMA INSTITUTIONAL","s":"","t":{e270:1}},{"p":"00510BS","n":"BCBS ALABAMA PROFESSIONAL","s":"","t":{e270:1}}],
"Blue Cross and Blue Shield of Hawaii":[{"p":"100937","n":"BCBS HAWAII","s":"","t":{e270:1}}],
"Blue Cross and Blue Shield of Illinois":[{"p":"G00621","n":"BCBS ILLINOIS","s":"HCSCIL","t":{e270:1}},{"p":"BCBSIL","n":"BCBS ILLINOIS","s":"BCBSILBCBS","t":{e270:0,pa_in:1,pa_out:1,ref:1}},{"p":"MCIL2","n":"BCBSIL COMMUNITY HEALTH PLANS","s":"MCIL2","t":{e270:0,pa_in:1,pa_out:1,ref:1,pa_det:0}}],
"Blue Cross and Blue Shield of Kansas":[{"p":"10034","n":"BCBS KANSAS","s":"","t":{e270:1}},{"p":"BCBSKS","n":"BCBS KANSAS","s":"BCBSKS","t":{e270:1}}],
"Blue Cross and Blue Shield of Kansas City":[{"p":"10473","n":"BCBS KANSAS CITY","s":"","t":{e270:1}}],
"Blue Cross and Blue Shield of Louisiana":[{"p":"53120","n":"BCBS LOUISIANA","s":"BCBSLA5312","t":{e270:1}},{"p":"72107","n":"BCBS LOUISIANA BLUE ADVANTAGE","s":"BAMLA","t":{e270:1}}],
"Blue Cross and Blue Shield of Massachusetts":[{"p":"700","n":"BCBS MASSACHUSETTS","s":"","t":{e270:1}}],
"Blue Cross and Blue Shield of Minnesota":[{"p":"00720","n":"BCBS MINNESOTA","s":"","t":{e270:1}},{"p":"00726","n":"BCBSMN BLUE PLUS MEDICAID (00726)","s":"BCBSMNMEDICAID","t":{e270:1}}],
"Blue Cross and Blue Shield of Montana":[{"p":"G00751","n":"BCBS MONTANA","s":"BCBSMT","t":{e270:1}},{"p":"BCBSMT","n":"BCBS MONTANA","s":"BCBSMT","t":{pa_in:1,pa_out:1,ref:1}}],
"Blue Cross and Blue Shield of Nebraska":[{"p":"77780","n":"BLUE SHIELD NEBRASKA","s":"77780","t":{e270:1}}],
"Blue Cross and Blue Shield of New Mexico":[{"p":"G00790","n":"BCBS NEW MEXICO","s":"HCSCNM","t":{e270:1}},{"p":"BCBSNM","n":"BCBS NEW MEXICO","s":"BCBSNMBCBS","t":{e270:0,pa_in:1,pa_out:1,ref:1}}],
"Blue Cross and Blue Shield of North Carolina":[{"p":"BCSNC","n":"BCBS NORTH CAROLINA","s":"","t":{e270:1}}],
"Blue Cross and Blue Shield of Oklahoma":[{"p":"G00840","n":"BCBS OKLAHOMA","s":"HCSCOK","t":{e270:1}},{"p":"BCBSOK","n":"BCBS OKLAHOMA","s":"BCBSOKBCBS","t":{e270:0,pa_in:1,pa_out:1,ref:1}}],
"Blue Cross and Blue Shield of South Carolina":[{"p":"00401","n":"BCBS SOUTH CAROLINA","s":"","t":{e270:1}}],
"Blue Cross and Blue Shield of Texas":[{"p":"G84980","n":"BCBS TEXAS","s":"BCBSTXG849","t":{e270:1}},{"p":"BCBSTX","n":"BCBS TEXAS","s":"BCBSTXBCBS","t":{e270:0,pa_in:1,pa_out:1,ref:1}},{"p":"WLPTXCAID","n":"BCBS TEXAS MEDICAID","s":"","t":{pa_in:1,pa_out:1,ref:1}}],
"Blue Cross and Blue Shield of Vermont":[{"p":"BCBSVT","n":"BCBS VERMONT","s":"BCBSVT","t":{e270:1}}],
"BlueCross BlueShield of Tennessee":[{"p":"SB890","n":"BCBS TENNESSEE","s":"","t":{e270:1}}],
"BlueShield of Northeastern New York":[{"p":"N5BLS","n":"BLUE SHIELD OF NORTHEASTERN NEW YORK","s":"N5BLS","t":{e270:1}}],
"Capital BlueCross":[{"p":"100952","n":"CAPITAL BLUE CROSS PENNSYLVANIA","s":"","t":{e270:1}}],
"CareFirst BlueCross BlueShield":[{"p":"190","n":"CAREFIRST BCBS","s":"","t":{e270:1}},{"p":"BCDCC","n":"CAREFIRST BCBS DISTRICT OF COLUMBIA","s":"","t":{e270:1}},{"p":"45281","n":"CAREFIRST BCBS COMMUNITY HEALTH PLAN MARYLAND","s":"","t":{e270:1}},{"p":"45282","n":"CAREFIRST BCBS MEDICARE ADVANTAGE","s":"","t":{e270:1}}],
"Excellus BlueCross BlueShield":[{"p":"100940","n":"EXCELLUS BCBS NEW YORK","s":"","t":{e270:1}}],
"Florida Blue":[{"p":"BCBSF","n":"FLORIDA BLUE (BCBS FLORIDA)","s":"BCBS_OF_FL","t":{e270:1,pa_in:1,pa_out:1,ref:1,pa_det:0}},{"p":"FBM01","n":"MEDICARE FLORIDA BLUE","s":"FBM01","t":{e270:1,pa_in:1,pa_out:1,ref:1,pa_det:0}}],
"Florida Explore My Plan":[{"p":"BCBSF","n":"FLORIDA BLUE (BCBS FLORIDA)","s":"BCBS_OF_FL","t":{e270:1,pa_in:1,pa_out:1,ref:1,pa_det:0}}],
"Highmark Blue Cross Blue Shield":[{"p":"54771I","n":"HIGHMARK BCBS PENNSYLVANIA INSTITUTIONAL","s":"54771I","t":{e270:1}},{"p":"100900","n":"BCBS PENNSYLVANIA NORTHEAST","s":"","t":{e270:1}},{"p":"100338","n":"BCBS PENNSYLVANIA NORTHWEST","s":"","t":{e270:1}}],
"Highmark Blue Cross Blue Shield Delaware":[{"p":"47181","n":"BCBS DELAWARE HIGHMARK HEALTH OPTIONS INCORPORATED","s":"","t":{e270:1}},{"p":"100026","n":"BCBS DELAWARE","s":"100026","t":{e270:1}}],
"Highmark Blue Cross Blue Shield West Virginia":[{"p":"54828","n":"HIGHMARK BCBS WEST VIRGINIA","s":"54828","t":{e270:1}},{"p":"100947","n":"BCBS WEST VIRGINIA","s":"","t":{e270:1}},{"p":"MTNST","n":"MOUNTAIN STATE BCBS WEST VIRGINIA","s":"","t":{e270:1}}],
"Highmark Blue Shield":[{"p":"54771","n":"HIGHMARK BCBS PENNSYLVANIA PROFESSIONAL","s":"54771","t":{e270:1}}],
"Highmark BlueCross BlueShield of Western New York":[{"p":"BCBSCAIDWNY","n":"HIGHMARK BCBS MMC, CHP, HARP, EP","s":"BCBSCAIDWNY","t":{e270:1,pa_in:0,pa_out:0,ref:0,pa_det:0}},{"p":"246","n":"HIGHMARK BCBS MMC, CHP, HARP, EP","s":"246","t":{e270:1,pa_det:0}}],
"Highmark BlueShield of Northeastern New York":[{"p":"N5BLS","n":"BLUE SHIELD OF NORTHEASTERN NEW YORK","s":"N5BLS","t":{e270:1}}],
"Horizon Blue Cross  Blue Shield of New Jersey":[{"p":"22099","n":"HORIZON BCBS NEW JERSEY","s":"HORIZON BCBSNJ","t":{e270:1,pa_det:0}},{"p":"22326","n":"HORIZON NEW JERSEY HEALTH","s":"HORIZON NJ HEALTH","t":{e270:1}},{"p":"100046","n":"BCBS NEW JERSEY","s":"","t":{e270:1}}],
"Independence Blue Cross":[{"p":"54704","n":"INDEPENDENCE BC PENNSLYVANIA PERSONAL CHOICE","s":"INDEPENDENCEBCPA","t":{e270:1}}],
"Premera Blue Cross":[{"p":"00430","n":"OTHER BLUE PLANS PREMERA BLUEEXCHANGE (SHARED ADMIN)","s":"PREMERABC","t":{e270:1}},{"p":"00430H","n":"PREMERA HMO","s":"PREMERABC","t":{e270:1}},{"p":"00934","n":"PREMERA BCBS WASHINGTON STATE","s":"PREMERAAK","t":{e270:1,ref:1}}],
"Regence BlueCross BlueShield":[{"p":"00851","n":"REGENCE BCBS OREGON","s":"","t":{e270:1,pa_in:1,pa_out:1,ref:1}},{"p":"00910","n":"REGENCE BCBS UTAH","s":"REGENCE_UT","t":{e270:1,pa_in:1,pa_out:1,ref:1}}],
"Regence BlueShield":[{"p":"00932","n":"REGENCE BS WASHINGTON","s":"REGENCE_WA","t":{e270:1,pa_in:1,pa_out:1,ref:1}}],
"Regence BlueShield of Idaho":[{"p":"00611","n":"REGENCE BS IDAHO","s":"REGENCEBSIDAHO","t":{e270:1,pa_in:1,pa_out:1,ref:1}}],
"Wellmark Blue Cross and Blue Shield Iowa":[{"p":"88848","n":"WELLMARK BCBS (IOWA, SOUTH DAKOTA)","s":"","t":{e270:1}}],
"Wellmark Blue Cross and Blue Shield South Dakota":[{"p":"88848","n":"WELLMARK BCBS (IOWA, SOUTH DAKOTA)","s":"","t":{e270:1}}]};

const A275=new Set(["Anthem Blue Cross", "Anthem Blue Cross and Blue Shield Colorado", "Anthem Blue Cross and Blue Shield Connecticut", "Blue Cross Blue Shield of Georgia", "Anthem Blue Cross and Blue Shield Indiana", "Anthem Blue Cross and Blue Shield Kentucky", "Anthem Blue Cross and Blue Shield Maine", "Anthem Blue Cross and Blue Shield Missouri", "Anthem Blue Cross and Blue Shield Nevada", "Anthem Blue Cross and Blue Shield New Hampshire", "Anthem Blue Cross and Blue Shield Ohio", "Anthem Blue Cross and Blue Shield Virginia", "Anthem Blue Cross and Blue Shield Wisconsin", "Anthem Blue Cross and Blue Shield", "Blue Cross and Blue Shield of Illinois", "Blue Cross and Blue Shield of Texas", "Blue Cross and Blue Shield of Montana", "Blue Cross and Blue Shield of New Mexico", "Blue Cross and Blue Shield of Oklahoma", "Regence BlueShield", "Regence BlueCross BlueShield", "Regence BlueShield of Idaho", "Premera Blue Cross"]);
